import fs from 'node:fs';import {HOME_TRANSFORMS} from '../dist/scene-layout.js';import {createModels} from '../dist/models.js';
// Deterministic glTF 2.0 binary exporter for the authored static meshes.
function exportGLB(roots,path){let chunks=[],offset=0;let j={asset:{version:'2.0',generator:'Yuanlong reference-study procedural mesh exporter'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:[],accessors:[],bufferViews:[],buffers:[],extensionsUsed:['KHR_materials_transmission','KHR_materials_ior','KHR_materials_volume','KHR_materials_sheen']};const materialMap=new Map(),textureMap=new Map();
function buffer(b,target){let pad=(4-b.length%4)%4;let idx=j.bufferViews.length;j.bufferViews.push({buffer:0,byteOffset:offset,byteLength:b.length,...(target?{target}:{})});chunks.push(b,Buffer.alloc(pad));offset+=b.length+pad;return idx}
function attribute(a,isIndex=false){let data=a.array;let view=buffer(Buffer.from(data.buffer,data.byteOffset,data.byteLength),isIndex?34963:34962);let idx=j.accessors.length;let v={bufferView:view,componentType:data instanceof Float32Array?5126:data instanceof Uint32Array?5125:5123,count:a.count,type:isIndex?'SCALAR':a.itemSize===3?'VEC3':'VEC2'};if(a.itemSize===3){v.min=[Infinity,Infinity,Infinity];v.max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<a.count;i++)for(let k=0;k<3;k++){v.min[k]=Math.min(v.min[k],data[i*3+k]);v.max[k]=Math.max(v.max[k],data[i*3+k])}}j.accessors.push(v);return idx;}
function material(m){if(materialMap.has(m.uuid))return materialMap.get(m.uuid);let index=j.materials.length;let o={name:m.name,pbrMetallicRoughness:{baseColorFactor:[m.color.r,m.color.g,m.color.b,1],metallicFactor:m.metalness,roughnessFactor:m.roughness},doubleSided:m.side===2};if(m.transmission)o.extensions={KHR_materials_transmission:{transmissionFactor:m.transmission},KHR_materials_ior:{ior:m.ior},KHR_materials_volume:{thicknessFactor:m.thickness,attenuationColor:m.attenuationColor.toArray(),attenuationDistance:m.attenuationDistance}};
if(m.sheen>0){o.extensions??={};o.extensions.KHR_materials_sheen={sheenColorFactor:m.sheenColor.toArray().map(v=>v*m.sheen),sheenRoughnessFactor:m.sheenRoughness};}
function tex(file){if(textureMap.has(file))return {index:textureMap.get(file)};let bv=buffer(fs.readFileSync('dist/assets/'+file));j.images??=[];j.textures??=[];let ti=j.textures.length;j.textures.push({source:j.images.length});j.images.push({bufferView:bv,mimeType:'image/png'});textureMap.set(file,ti);return {index:ti};}
if(m.name==='Printed paper')o.pbrMetallicRoughness.baseColorTexture=tex('research-print.png');
let nm=m.name==='Linen'?'linen':m.name.includes('mineral')?'stone':m.name==='Paper'?'paper':null;if(nm){o.normalTexture={...tex(nm+'-normal.png'),scale:.35};o.pbrMetallicRoughness.baseColorTexture=tex(nm+'-color.png');}
j.materials.push(o);materialMap.set(m.uuid,index);return index;}
function node(obj){let idx=j.nodes.length;let n={name:obj.name,translation:obj.position.toArray(),rotation:obj.quaternion.toArray(),scale:obj.scale.toArray()};j.nodes.push(n);if(obj.isMesh){let g=obj.geometry;let a={POSITION:attribute(g.attributes.position),NORMAL:attribute(g.attributes.normal)};if(g.attributes.uv)a.TEXCOORD_0=attribute(g.attributes.uv);let p={attributes:a,material:material(obj.material)};if(g.index)p.indices=attribute(g.index,true);n.mesh=j.meshes.length;j.meshes.push({name:obj.name,primitives:[p]});}if(obj.children.length)n.children=obj.children.map(node);return idx;}
j.scenes[0].nodes=roots.map(node);j.buffers=[{byteLength:offset}];let raw=Buffer.from(JSON.stringify(j));let json=Buffer.concat([raw,Buffer.alloc((4-raw.length%4)%4,32)]);let bin=Buffer.concat(chunks);let h=Buffer.alloc(12),jh=Buffer.alloc(8),bh=Buffer.alloc(8);h.writeUInt32LE(0x46546c67);h.writeUInt32LE(2,4);h.writeUInt32LE(12+8+json.length+8+bin.length,8);jh.writeUInt32LE(json.length);jh.writeUInt32LE(0x4e4f534a,4);bh.writeUInt32LE(bin.length);bh.writeUInt32LE(0x004e4942,4);fs.writeFileSync(path,Buffer.concat([h,jh,json,bh,bin]));return {file:path,meshes:j.meshes.length,bytes:fs.statSync(path).size};}
let roots=createModels();for(let i=0;i<3;i++)console.log(exportGLB([roots[i]],'dist/models/'+['writing','architecture','research'][i]+'.glb'));roots.forEach((m,i)=>{const f=HOME_TRANSFORMS[i];m.position.set(f[0],0,f[1]);m.scale.set(f[2],f[3],f[5]);m.rotation.y=f[4]});console.log(exportGLB(roots,'dist/models/portfolio-scene.glb'));
