import assert from 'node:assert/strict';
import {createFrameRuntime,FRAME_ACTIVE,FRAME_RENDER} from '../frame-runtime.js';
let clock=42000,callback,draws=0,observed=0;
globalThis.document={hidden:false};
Object.defineProperty(globalThis,'performance',{value:{now:()=>clock},configurable:true});
globalThis.gsap={ticker:{add(fn){callback=fn;},remove(fn){if(callback===fn)callback=null;}}};
const runtime=createFrameRuntime(()=>draws++);
let active=true;runtime.add((dt,now)=>{observed=now;return active?FRAME_ACTIVE:0;});
runtime.request();callback(.1);
assert.equal(observed,42000,'Must use performance clock, not lag-smoothed GSAP time');assert.equal(draws,1);
clock=42100;active=false;callback(.2);assert.equal(runtime.running,false);
runtime.setPaused(true);runtime.request(FRAME_RENDER);assert.equal(runtime.running,false);
runtime.setPaused(false);assert.equal(runtime.running,true);callback(.3);assert.equal(draws,2);assert.equal(runtime.running,false);
runtime.dispose();delete globalThis.gsap;
let rafId=0,scheduled=new Map();
globalThis.requestAnimationFrame=fn=>{scheduled.set(++rafId,fn);return rafId;};
globalThis.cancelAnimationFrame=id=>scheduled.delete(id);
const fallback=createFrameRuntime(()=>draws++);fallback.request();fallback.request();assert.equal(scheduled.size,1,'Only one RAF owner');
const fn=scheduled.values().next().value;scheduled.clear();clock+=16;fn(clock);assert.equal(fallback.running,false);fallback.dispose();
console.log('PASS: shared monotonic clock, idle sleep, pause/resume, single RAF driver.');
